{{- if (.Values.Secret.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
{{- range $key, $value := .Values.Secret.Data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}